name: Close PR

on:
  pull_request:
      types: [ closed ]
  workflow_dispatch:

env:
  app-name: "loadtestapi"
  rg-name: "RG-LoadTestk6"
  slot-name: pr-${{ github.event.number }}

jobs:
  clean_up:
    runs-on: ubuntu-latest

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Az Account Show
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az account set --subscription 0684d3a9-f0d2-4443-90e9-734663273ce9
      
      - name: Delete PR Slot
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az webapp deployment slot delete --name ${{ env.app-name }} --resource-group ${{ env.rg-name }} --slot ${{ env.slot-name }} --subscription 0684d3a9-f0d2-4443-90e9-734663273ce9